apps:guide:
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\nGuide\\n"
apps:proxy-container:
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\nProxy Container\\n"
apps:website:
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\nDocumentation\\n"
packages:collection:
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\ncollection\\n"
packages:core:
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\ncore\\n"
packages:client:
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\nclient\\n"
packages:formatters:
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\nformatters\\n"
packages:identity:
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\nidentity\\n"
packages:rest:
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\nrest\\n"
packages:util:
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\nutil\\n"
packages:voice:
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\nvoice\\n"
packages:ws:
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\nws\\n"
