packages:api-extractor:
  - changed-files:
      - any-glob-to-any-file:
          - packages/api-extractor/*
          - packages/api-extractor/**/*
packages:api-extractor-model:
  - changed-files:
      - any-glob-to-any-file:
          - packages/api-extractor-model/*
          - packages/api-extractor-model/**/*
packages:collection:
  - changed-files:
      - any-glob-to-any-file:
          - packages/collection/*
          - packages/collection/**/*
packages:discord.js:
  - changed-files:
      - any-glob-to-any-file:
          - packages/discord.js/*
          - packages/discord.js/**/*
packages:docgen:
  - changed-files:
      - any-glob-to-any-file:
          - packages/docgen/*
          - packages/docgen/**/*
packages:formatters:
  - changed-files:
      - any-glob-to-any-file:
          - packages/formatters/*
          - packages/formatters/**/*
packages:rest:
  - changed-files:
      - any-glob-to-any-file:
          - packages/rest/*
          - packages/rest/**/*
packages:util:
  - changed-files:
      - any-glob-to-any-file:
          - packages/util/*
          - packages/util/**/*
packages:ws:
  - changed-files:
      - any-glob-to-any-file:
          - packages/ws/*
          - packages/ws/**/*
