name: 'Upload documentation'
description: 'Uploads docs.api.json files to object storage and updates per-package version manifests'
inputs:
  package:
    description: 'The package string'
  version:
    description: 'The semver string'
runs:
  using: node20
  main: ../../dist/uploadDocumentation/index.js
